### ISSUE TITLE
Import into blender issue

### ISSUE THREAD

**Issue by Postcanta** [wurunduk/blender-p3d-import-export#5]
"Python: Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-p3d-import-export-master\ops\ops.py", line 83, in execute
    return import_cdp3d.load(self, context, **keywords)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-p3d-import-export-master\ops\import_cdp3d.py", line 198, in load
    p.read(file)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-p3d-import-export-master\crashday\p3d.py", line 326, in read
    p.read(file, self.textures, self.num_textures)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-p3d-import-export-master\crashday\p3d.py", line 190, in read
    poly.read(file)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-p3d-import-export-master\crashday\p3d.py", line 119, in read
    ) = rf(file, '<H2fH2fH2f')
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-p3d-import-export-master\crashday\p3d.py", line 7, in rf
    answer = struct.unpack(format, file.read(struct.calcsize(format)))
struct.error: unpack requires a buffer of 30 bytes

location: <unknown location>:-1"

Trying to modify a weapon pack for arma. Can't import the weapons into blender

**Comment by wurunduk** [comment]
Hi. This plugin is made specifically to open Crashday .p3d models. It wont work for arma sadly.

Maybe this plugin is what you are looking for: [ArmAToolbox](https://github.com/AlwarrenSidh/ArmAToolbox)
